-- begin HERA_PARTY_ADDRESS
alter table HERA_PARTY_ADDRESS add constraint FK_HERA_PARTY_ADDRESS_ON_PARTY foreign key (PARTY_ID) references HERA_PARTY(ID)^
alter table HERA_PARTY_ADDRESS add constraint FK_HERA_PARTY_ADDRESS_ON_COUNTRY foreign key (COUNTRY_ID) references HERA_COUNTRY(ID)^
create index IDX_HERA_PARTY_ADDRESS_ON_PARTY on HERA_PARTY_ADDRESS (PARTY_ID)^
create index IDX_HERA_PARTY_ADDRESS_ON_COUNTRY on HERA_PARTY_ADDRESS (COUNTRY_ID)^
-- end HERA_PARTY_ADDRESS
-- begin HERA_PARTY_ROLE
alter table HERA_PARTY_ROLE add constraint FK_HERA_PARTY_ROLE_ON_PARTY foreign key (PARTY_ID) references HERA_PARTY(ID)^
create index IDX_HERA_PARTY_ROLE_ON_PARTY on HERA_PARTY_ROLE (PARTY_ID)^
-- end HERA_PARTY_ROLE
-- begin HERA_PARTY_CONTACT
alter table HERA_PARTY_CONTACT add constraint FK_HERA_PARTY_CONTACT_ON_PARTY foreign key (PARTY_ID) references HERA_PARTY(ID)^
create index IDX_HERA_PARTY_CONTACT_ON_PARTY on HERA_PARTY_CONTACT (PARTY_ID)^
-- end HERA_PARTY_CONTACT
-- begin HERA_PARTY_IDENTIFIER
alter table HERA_PARTY_IDENTIFIER add constraint FK_HERA_PARTY_IDENTIFIER_ON_PARTY foreign key (PARTY_ID) references HERA_PARTY(ID)^
create index IDX_HERA_PARTY_IDENTIFIER_ON_PARTY on HERA_PARTY_IDENTIFIER (PARTY_ID)^
-- end HERA_PARTY_IDENTIFIER
-- begin HERA_PARTY_RELATIONSHIP
alter table HERA_PARTY_RELATIONSHIP add constraint FK_HERA_PARTY_RELATIONSHIP_ON_FROM_PARTY_ROLE foreign key (FROM_PARTY_ROLE_ID) references HERA_PARTY_ROLE(ID)^
alter table HERA_PARTY_RELATIONSHIP add constraint FK_HERA_PARTY_RELATIONSHIP_ON_TO_PARTY_ROLE foreign key (TO_PARTY_ROLE_ID) references HERA_PARTY_ROLE(ID)^
create index IDX_HERA_PARTY_RELATIONSHIP_ON_FROM_PARTY_ROLE on HERA_PARTY_RELATIONSHIP (FROM_PARTY_ROLE_ID)^
create index IDX_HERA_PARTY_RELATIONSHIP_ON_TO_PARTY_ROLE on HERA_PARTY_RELATIONSHIP (TO_PARTY_ROLE_ID)^
-- end HERA_PARTY_RELATIONSHIP
-- begin HERA_PARTY
alter table HERA_PARTY add constraint FK_HERA_PARTY_ON_PHOTO_IMAGE foreign key (PHOTO_IMAGE_ID) references SYS_FILE(ID)^
create index IDX_HERA_PARTY_ON_PHOTO_IMAGE on HERA_PARTY (PHOTO_IMAGE_ID)^
-- end HERA_PARTY
-- begin HERA_POSITION
alter table HERA_POSITION add constraint FK_HERA_POSITION_ON_POSITION_TYPE foreign key (POSITION_TYPE_ID) references HERA_POSITION_TYPE(ID)^
alter table HERA_POSITION add constraint FK_HERA_POSITION_ON_BUDGET_ITEM foreign key (BUDGET_ITEM_ID) references HERA_BUDGET_ITEM(ID)^
alter table HERA_POSITION add constraint FK_HERA_POSITION_ON_WITHIN_ORGANIZATION foreign key (WITHIN_ORGANIZATION_ID) references HERA_PARTY(ID)^
create index IDX_HERA_POSITION_ON_POSITION_TYPE on HERA_POSITION (POSITION_TYPE_ID)^
create index IDX_HERA_POSITION_ON_BUDGET_ITEM on HERA_POSITION (BUDGET_ITEM_ID)^
create index IDX_HERA_POSITION_ON_WITHIN_ORGANIZATION on HERA_POSITION (WITHIN_ORGANIZATION_ID)^
-- end HERA_POSITION
-- begin HERA_POSITION_FULFILLMENT
alter table HERA_POSITION_FULFILLMENT add constraint FK_HERA_POSITION_FULFILLMENT_ON_ACCEPTED_BY foreign key (ACCEPTED_BY_ID) references HERA_PARTY(ID)^
alter table HERA_POSITION_FULFILLMENT add constraint FK_HERA_POSITION_FULFILLMENT_ON_FULFILLMENT_OF foreign key (FULFILLMENT_OF_ID) references HERA_POSITION(ID)^
create index IDX_HERA_POSITION_FULFILLMENT_ON_ACCEPTED_BY on HERA_POSITION_FULFILLMENT (ACCEPTED_BY_ID)^
create index IDX_HERA_POSITION_FULFILLMENT_ON_FULFILLMENT_OF on HERA_POSITION_FULFILLMENT (FULFILLMENT_OF_ID)^
-- end HERA_POSITION_FULFILLMENT
-- begin HERA_POSITION_TYPE
alter table HERA_POSITION_TYPE add constraint FK_HERA_POSITION_TYPE_ON_COMPANY foreign key (COMPANY_ID) references HERA_PARTY_ROLE(ID)^
create index IDX_HERA_POSITION_TYPE_ON_COMPANY on HERA_POSITION_TYPE (COMPANY_ID)^
-- end HERA_POSITION_TYPE
-- begin HERA_POSITION_RESPONSIBILITY
alter table HERA_POSITION_RESPONSIBILITY add constraint FK_HERA_POSITION_RESPONSIBILITY_ON_POSITION foreign key (POSITION_ID) references HERA_POSITION(ID)^
create index IDX_HERA_POSITION_RESPONSIBILITY_ON_POSITION on HERA_POSITION_RESPONSIBILITY (POSITION_ID)^
-- end HERA_POSITION_RESPONSIBILITY
-- begin HERA_POSITION_TYPE_CLASS
alter table HERA_POSITION_TYPE_CLASS add constraint FK_HERA_POSITION_TYPE_CLASS_ON_CLASSIFICATION_TYPE foreign key (CLASSIFICATION_TYPE_ID) references HERA_POSITION_CLASSIFICATION_TYPE(ID)^
alter table HERA_POSITION_TYPE_CLASS add constraint FK_HERA_POSITION_TYPE_CLASS_ON_POSITION_TYPE foreign key (POSITION_TYPE_ID) references HERA_POSITION_TYPE(ID)^
create index IDX_HERA_POSITION_TYPE_CLASS_ON_CLASSIFICATION_TYPE on HERA_POSITION_TYPE_CLASS (CLASSIFICATION_TYPE_ID)^
create index IDX_HERA_POSITION_TYPE_CLASS_ON_POSITION_TYPE on HERA_POSITION_TYPE_CLASS (POSITION_TYPE_ID)^
-- end HERA_POSITION_TYPE_CLASS
