-- begin HERA_PARTY_ADDRESS
alter table HERA_PARTY_ADDRESS add constraint FK_HERA_PARTY_ADDRESS_ON_PARTY foreign key (PARTY_ID) references HERA_PARTY(ID)^
alter table HERA_PARTY_ADDRESS add constraint FK_HERA_PARTY_ADDRESS_ON_COUNTRY foreign key (COUNTRY_ID) references HERA_COUNTRY(ID)^
create index IDX_HERA_PARTY_ADDRESS_ON_PARTY on HERA_PARTY_ADDRESS (PARTY_ID)^
create index IDX_HERA_PARTY_ADDRESS_ON_COUNTRY on HERA_PARTY_ADDRESS (COUNTRY_ID)^
-- end HERA_PARTY_ADDRESS
-- begin HERA_PARTY_ROLE
alter table HERA_PARTY_ROLE add constraint FK_HERA_PARTY_ROLE_ON_PARTY foreign key (PARTY_ID) references HERA_PARTY(ID)^
create index IDX_HERA_PARTY_ROLE_ON_PARTY on HERA_PARTY_ROLE (PARTY_ID)^
-- end HERA_PARTY_ROLE
-- begin HERA_PARTY_CONTACT
alter table HERA_PARTY_CONTACT add constraint FK_HERA_PARTY_CONTACT_ON_PARTY foreign key (PARTY_ID) references HERA_PARTY(ID)^
create index IDX_HERA_PARTY_CONTACT_ON_PARTY on HERA_PARTY_CONTACT (PARTY_ID)^
-- end HERA_PARTY_CONTACT
-- begin HERA_PARTY_IDENTIFIER
alter table HERA_PARTY_IDENTIFIER add constraint FK_HERA_PARTY_IDENTIFIER_ON_PARTY foreign key (PARTY_ID) references HERA_PARTY(ID)^
create index IDX_HERA_PARTY_IDENTIFIER_ON_PARTY on HERA_PARTY_IDENTIFIER (PARTY_ID)^
-- end HERA_PARTY_IDENTIFIER
-- begin HERA_PARTY_RELATIONSHIP
alter table HERA_PARTY_RELATIONSHIP add constraint FK_HERA_PARTY_RELATIONSHIP_ON_FROM_PARTY_ROLE foreign key (FROM_PARTY_ROLE_ID) references HERA_PARTY_ROLE(ID)^
alter table HERA_PARTY_RELATIONSHIP add constraint FK_HERA_PARTY_RELATIONSHIP_ON_TO_PARTY_ROLE foreign key (TO_PARTY_ROLE_ID) references HERA_PARTY_ROLE(ID)^
create index IDX_HERA_PARTY_RELATIONSHIP_ON_FROM_PARTY_ROLE on HERA_PARTY_RELATIONSHIP (FROM_PARTY_ROLE_ID)^
create index IDX_HERA_PARTY_RELATIONSHIP_ON_TO_PARTY_ROLE on HERA_PARTY_RELATIONSHIP (TO_PARTY_ROLE_ID)^
-- end HERA_PARTY_RELATIONSHIP
