alter table HERA_PARTY_IDENTIFIER add constraint FK_HERA_PARTY_IDENTIFIER_ON_PARTY foreign key (PARTY_ID) references HERA_PARTY(ID);
create index IDX_HERA_PARTY_IDENTIFIER_ON_PARTY on HERA_PARTY_IDENTIFIER (PARTY_ID);
