alter table HERA_PAY_HISTORY add constraint FK_HERA_PAY_HISTORY_ON_EMPLOYMENT foreign key (EMPLOYMENT_ID) references HERA_PARTY_RELATIONSHIP(ID);
alter table HERA_PAY_HISTORY add constraint FK_HERA_PAY_HISTORY_ON_SALARY_STEP foreign key (SALARY_STEP_ID) references HERA_SALARY_STEP(ID);
create index IDX_HERA_PAY_HISTORY_ON_EMPLOYMENT on HERA_PAY_HISTORY (EMPLOYMENT_ID);
create index IDX_HERA_PAY_HISTORY_ON_SALARY_STEP on HERA_PAY_HISTORY (SALARY_STEP_ID);
