alter table HERA_POSITION_STRUCTURE add constraint FK_HERA_POSITION_STRUCTURE_ON_POSITION foreign key (POSITION_ID) references HERA_POSITION(ID);
alter table HERA_POSITION_STRUCTURE add constraint FK_HERA_POSITION_STRUCTURE_ON_MANAGED_BY foreign key (MANAGED_BY_ID) references HERA_POSITION(ID);
create index IDX_HERA_POSITION_STRUCTURE_ON_POSITION on HERA_POSITION_STRUCTURE (POSITION_ID);
create index IDX_HERA_POSITION_STRUCTURE_ON_MANAGED_BY on HERA_POSITION_STRUCTURE (MANAGED_BY_ID);
