alter table HERA_TIME_ENTRY add constraint FK_HERA_TIME_ENTRY_ON_TIMESHEET foreign key (TIMESHEET_ID) references HERA_TIMESHEET(ID);
alter table HERA_TIME_ENTRY add constraint FK_HERA_TIME_ENTRY_ON_WORKEFFORT foreign key (WORKEFFORT_ID) references HERA_WORKEFFORT(ID);
create index IDX_HERA_TIME_ENTRY_ON_TIMESHEET on HERA_TIME_ENTRY (TIMESHEET_ID);
create index IDX_HERA_TIME_ENTRY_ON_WORKEFFORT on HERA_TIME_ENTRY (WORKEFFORT_ID);
