alter table HERA_EMPLOYEE_RANK add constraint FK_HERA_EMPLOYEE_RANK_ON_EMPLYEE foreign key (EMPLYEE_ID) references HERA_PARTY_ROLE(ID);
alter table HERA_EMPLOYEE_RANK add constraint FK_HERA_EMPLOYEE_RANK_ON_RANK_TYPE foreign key (RANK_TYPE_ID) references HERA_RANK(ID);
create index IDX_HERA_EMPLOYEE_RANK_ON_EMPLYEE on HERA_EMPLOYEE_RANK (EMPLYEE_ID);
create index IDX_HERA_EMPLOYEE_RANK_ON_RANK_TYPE on HERA_EMPLOYEE_RANK (RANK_TYPE_ID);
