alter table HERA_TIMESHEET add constraint FK_HERA_TIMESHEET_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references HERA_PARTY_ROLE(ID);
create index IDX_HERA_TIMESHEET_ON_EMPLOYEE on HERA_TIMESHEET (EMPLOYEE_ID);
