alter table HERA_POSITION_FULFILLMENT alter column ACCEPTED_BY_ID rename to ACCEPTED_BY_ID__U00517 ^
alter table HERA_POSITION_FULFILLMENT drop constraint FK_HERA_POSITION_FULFILLMENT_ON_ACCEPTED_BY ;
drop index IDX_HERA_POSITION_FULFILLMENT_ON_ACCEPTED_BY ;
alter table HERA_POSITION_FULFILLMENT add column ACCEPTED_BY_ID varchar(36) ;
