alter table HERA_POSITION_TYPE add constraint FK_HERA_POSITION_TYPE_ON_COMPANY foreign key (COMPANY_ID) references HERA_PARTY_ROLE(ID);
create index IDX_HERA_POSITION_TYPE_ON_COMPANY on HERA_POSITION_TYPE (COMPANY_ID);
