alter table HERA_SALARY_STEP add constraint FK_HERA_SALARY_STEP_ON_PAY_GRADE foreign key (PAY_GRADE_ID) references HERA_PAY_GRADE(ID);
create index IDX_HERA_SALARY_STEP_ON_PAY_GRADE on HERA_SALARY_STEP (PAY_GRADE_ID);
