alter table HERA_PARTY_ADDRESS add constraint FK_HERA_PARTY_ADDRESS_ON_COUNTRY foreign key (COUNTRY_ID) references HERA_COUNTRY(ID);
create index IDX_HERA_PARTY_ADDRESS_ON_COUNTRY on HERA_PARTY_ADDRESS (COUNTRY_ID);
