alter table HERA_ATTENDANCE add constraint FK_HERA_ATTENDANCE_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references HERA_PARTY_ROLE(ID);
alter table HERA_ATTENDANCE add constraint FK_HERA_ATTENDANCE_ON_LEAVE_PERMITTED_BY foreign key (LEAVE_PERMITTED_BY_ID) references HERA_PARTY_ROLE(ID);
alter table HERA_ATTENDANCE add constraint FK_HERA_ATTENDANCE_ON_EXTRA_HOUR_PERMITTED_BY foreign key (EXTRA_HOUR_PERMITTED_BY_ID) references HERA_PARTY_ROLE(ID);
alter table HERA_ATTENDANCE add constraint FK_HERA_ATTENDANCE_ON_TIMESHEET foreign key (TIMESHEET_ID) references HERA_TIMESHEET(ID);
create index IDX_HERA_ATTENDANCE_ON_EMPLOYEE on HERA_ATTENDANCE (EMPLOYEE_ID);
create index IDX_HERA_ATTENDANCE_ON_LEAVE_PERMITTED_BY on HERA_ATTENDANCE (LEAVE_PERMITTED_BY_ID);
create index IDX_HERA_ATTENDANCE_ON_EXTRA_HOUR_PERMITTED_BY on HERA_ATTENDANCE (EXTRA_HOUR_PERMITTED_BY_ID);
create index IDX_HERA_ATTENDANCE_ON_TIMESHEET on HERA_ATTENDANCE (TIMESHEET_ID);
