alter table HERA_PARTY_ROLE add constraint FK_HERA_PARTY_ROLE_ON_PARENT_COMPANY foreign key (PARENT_COMPANY_ID) references HERA_PARTY_ROLE(ID);
create index IDX_HERA_PARTY_ROLE_ON_PARENT_COMPANY on HERA_PARTY_ROLE (PARENT_COMPANY_ID);
