alter table HERA_POSITION add constraint FK_HERA_POSITION_ON_POSITION_TYPE foreign key (POSITION_TYPE_ID) references HERA_POSITION_TYPE(ID);
alter table HERA_POSITION add constraint FK_HERA_POSITION_ON_BUDGET_ITEM foreign key (BUDGET_ITEM_ID) references HERA_BUDGET_ITEM(ID);
alter table HERA_POSITION add constraint FK_HERA_POSITION_ON_WITHIN_ORGANIZATION foreign key (WITHIN_ORGANIZATION_ID) references HERA_PARTY(ID);
create index IDX_HERA_POSITION_ON_POSITION_TYPE on HERA_POSITION (POSITION_TYPE_ID);
create index IDX_HERA_POSITION_ON_BUDGET_ITEM on HERA_POSITION (BUDGET_ITEM_ID);
create index IDX_HERA_POSITION_ON_WITHIN_ORGANIZATION on HERA_POSITION (WITHIN_ORGANIZATION_ID);
