alter table HERA_BANK_ACCOUNT add constraint FK_HERA_BANK_ACCOUNT_ON_CURRENCY foreign key (CURRENCY_ID) references HERA_CURRENCY(ID);
create index IDX_HERA_BANK_ACCOUNT_ON_CURRENCY on HERA_BANK_ACCOUNT (CURRENCY_ID);
