alter table HERA_EMPLOYEE_REQUEST add constraint FK_HERA_EMPLOYEE_REQUEST_ON_MANAGER foreign key (MANAGER_ID) references HERA_PARTY_ROLE(ID);
create index IDX_HERA_EMPLOYEE_REQUEST_ON_MANAGER on HERA_EMPLOYEE_REQUEST (MANAGER_ID);
