alter table HERA_EMPLOYEE_TASK add constraint FK_HERA_EMPLOYEE_TASK_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references HERA_PARTY_ROLE(ID);
create index IDX_HERA_EMPLOYEE_TASK_ON_EMPLOYEE on HERA_EMPLOYEE_TASK (EMPLOYEE_ID);
