alter table HERA_QUESTIONAIRE add constraint FK_HERA_QUESTIONAIRE_ON_QUESTIONAIRETYPE foreign key (QUESTIONAIRETYPE_ID) references HERA_QUESTIONAIRE_TYPE(ID);
alter table HERA_QUESTIONAIRE add constraint FK_HERA_QUESTIONAIRE_ON_MAKER foreign key (MAKER_ID) references HERA_PARTY_ROLE(ID);
create index IDX_HERA_QUESTIONAIRE_ON_QUESTIONAIRETYPE on HERA_QUESTIONAIRE (QUESTIONAIRETYPE_ID);
create index IDX_HERA_QUESTIONAIRE_ON_MAKER on HERA_QUESTIONAIRE (MAKER_ID);
