alter table HERA_EMPLOYEE_USER add constraint FK_HERA_EMPLOYEE_USER_ON_USER foreign key (USER_ID) references SEC_USER(ID);
alter table HERA_EMPLOYEE_USER add constraint FK_HERA_EMPLOYEE_USER_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references HERA_PARTY_ROLE(ID);
create index IDX_HERA_EMPLOYEE_USER_ON_USER on HERA_EMPLOYEE_USER (USER_ID);
create index IDX_HERA_EMPLOYEE_USER_ON_EMPLOYEE on HERA_EMPLOYEE_USER (EMPLOYEE_ID);
