alter table HERA_PARTY_ROLE add constraint FK_HERA_PARTY_ROLE_ON_PARTYROLETYPE foreign key (PARTYROLETYPE_ID) references HERA_PARTY_ROLE_TYPE(ID);
create index IDX_HERA_PARTY_ROLE_ON_PARTYROLETYPE on HERA_PARTY_ROLE (PARTYROLETYPE_ID);
